name: PlayerDataConverter
main: rocks.craftclue.playerdataconverter.PlayerDataConverter
version: 1.1.1
author: cluefuhfake
commands:
  convertplayerdata:
    description: Convert old pre-UUID user world files to UUID ones
    usage: You may only use this command from the console
  convertessentialsplayerdata:
    description: Convert old pre-UUID Essentials user file to UUID ones
    usage: You may only use this command from the console